config/routes.rb
Railsjam::Application.routes.draw do

  match 'logout', :to => 'user_sessions#destroy', :as => "logout"
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'not_found', :to=>"home#page_not_found", :as=>"not_found"

  


  resources :attachments 
  resources :events
  resources :events do
    resource :attendees
  end

  resources :users
  match '/signup', :to => 'users#new'
  
  match 'account', :to=>'users#edit'

  resources :posts
  resources :pages
  resource :user_session
  
  resources :password_resets
  
  resources :galleries 
  resources :photos 
  
  resources :sponsors
  
  resources :sponsors do
     resources :photos    
  end
  
  
  resources :galleries do
    resources :photos 
  end
  
  resources :presentations 
 
  
  get "home/index"

  match 'blog/:id', :to=> 'posts#show'
  match ':id', :to=> 'pages#show', :id=>nil
    
    
    
  resources :home
  root :to => "home#index"

end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  

  validates :title,  :presence=>true, :uniqueness=>true
  validates :body, :presence=>true
  validates :event_id, :presence=>true
  validates :speaker_link, :link=>true, :if=>:has_speaker_link
  validates :link, :link=>true , :if=>:has_link

  has_friendly_id :title, :use_slug => true  
  belongs_to :event
  has_many :attachments, :as => 'attachable', :dependent => :destroy
  accepts_nested_attributes_for :attachments, :allow_destroy => true 
  
  private
  
  def has_link
    if self.link and !self.link.blank?
      return true
    end
  end
  
  def has_speaker_link
    if self.speaker_link and !self.speaker_link.blank?
      return true
    end 
  end
  
  
  
  
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  
  filter_access_to :all
  
  
  def index
    
    #@events = Event.all 
    @presentations = Presentation.order("created_at DESC").paginate( :page => params[:page], :per_page => 2)

    respond_to do |format|
      format.html
    end
  end


  def show
    @presentation = Presentation.find(params[:id])
    @title = "RailsJam | #{@presentation.title}" 
    respond_to do |format|
      format.html
    end
  end

  def new
    @presentation = Presentation.new
    1.times { @presentation.attachments.build }
    respond_to do |format|
      format.html 
    end
  end


  def edit
    @presentation = Presentation.find(params[:id])
    if @presentation.attachments and @presentation.attachments.size == 0
      1.times { @presentation.attachments.build }      
    end
  end


  def create
    @presentation = Presentation.new(params[:presentation])

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to(@presentation, :notice => 'Presentation was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end


  def update
    @presentation = Presentation.find(params[:id])

    respond_to do |format|
      if @presentation.update_attributes(params[:presentation])
        format.html { redirect_to(@presentation, :notice => 'Presentation was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end


  def destroy
    @presentation = Presentation.find(params[:id])
    @presentation.destroy

    respond_to do |format|
      format.html { redirect_to(presentations_url) }
      format.xml  { head :ok }
    end
  end
end

app/views/presentations/_file.html.haml
%div{:id=>p ? "file_field_#{p.id}" : "file_field", :class=>"attach_file"}
  %label{:for => "presentation_photo_attributes_0_file"} File
  %input{:name => "presentation[attachments_attributes][0][file]", :type => "file", :class=>"file_field"}/

  -if p
    %input{:name => "presentation[attachments_attributes][0][id]", :type => "hidden", :value => p.id }/

app/views/presentations/_form.html.haml
= form_for @presentation, :html=>{:multipart=>true} do |f|
  = render "shared/error_messages", :target => @presentation
  .field
    = f.label :title
    = f.text_field :title, :class=>"input"
  .field
    = f.label :event_id
    = select("presentation", "event_id", Event.all.collect {|p| [ p.name, p.id ] }, {:prompt => 'Select Event'}, :class=>"input")

  .field
    = f.label :link 
    = f.text_field :link, :class=>"input"

  .field
    = f.label :speaker_name 
    = f.text_field :speaker_name , :class=>"input"

  .field
    = f.label :speaker_link 
    = f.text_field :speaker_link, :class=>"input"
        
  .field
    = f.label :body
    = f.text_area :body, :class=>"textarea"

  -if @presentation.attachments and @presentation.attachments.size > 0 and  @presentation.attachments[0].file and !@presentation.attachments[0].file.url.include?('missing')
    -@presentation.attachments.each do |p|
      %li{:id=>"file_"+p.id.to_s}
        =link_to "View File", p.file.url, :target=>"_blank"
        %br/
        =link_to "Delete", attachment_url(p.id), :method=>:delete, :confirm=>"Are you sure you want to delete this file?", :remote=>:true, :class=>"alert"
      =render "file", :p=>p
      
  
  .field 
    %p Add a file for this presentation
    =render "file", :p=>p
    
    
  .actions
    = f.submit 'Save', :class=>"button"

app/views/presentations/edit.html.haml
%h1 Edit Presentation

= render 'form'
.show-links
  =link_to 'Back', posts_path
  = link_to 'Help', "http://redcloth.org/textile/writing-paragraph-text/", :target=>"_blank"

app/views/presentations/index.html.haml
-content_for :sidebar do
  =render :partial => "shared/sidebar"
  
.body

  - if permitted_to? :create, :presentations 
    .index_actions
      =# link_to 'New Presentation', new_presentation_path, :class=>"new_link"
      

  -@presentations.each do |p|
    %h3= link_to p.title, presentation_url(p)

    -if p.speaker_name and !p.speaker_name.blank?
      %ul.speaker-details
        %li
          by: 
          -if (p.speaker_link and !p.speaker_link.blank?)
            = link_to p.speaker_name, p.speaker_link, :target=>"_blank"
          -else
            p.speaker_name

     
      = raw p.body 
      
      -if p.attachments and p.attachments.size > 0
        -p.attachments.each do |a|
          =link_to "Download", a.file.url
          
      
      - if permitted_to? :edit, :presentations  
        = link_to 'Edit', edit_presentation_path(p) 
        
  =will_paginate @presentations

     

app/views/presentations/new.html.haml
%h1 New Presentation

= render 'form'
.show-links
  =link_to 'Back', posts_path
  = link_to 'Help', "http://redcloth.org/textile/writing-paragraph-text/", :target=>"_blank"

app/views/presentations/show.html.haml
-content_for :sidebar do
  =render :partial => "shared/sidebar"
  
.body
  %h2= @presentation.title 
  -if @presentation.speaker_name and !@presentation.speaker_name.blank?
    %ul.speaker-details
      %li
        by: 
        -if (@presentation.speaker_link and !@presentation.speaker_link.blank?)
          = link_to @presentation.speaker_name, @presentation.speaker_link, :target=>"_blank"
        -else
          = @presentation.speaker_name

  = raw @presentation.body
  .clear
  -if current_user and current_user.user_type=="Admin"
    = link_to 'Edit', edit_presentation_path(@presentation)
    \|
    = link_to 'Back', presentations_path
    