config/routes.rb
Railsjam::Application.routes.draw do

  match 'logout', :to => 'user_sessions#destroy', :as => "logout"
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'not_found', :to=>"home#page_not_found", :as=>"not_found"

  


  resources :attachments 
  resources :events
  resources :events do
    resource :attendees
  end

  resources :users
  match '/signup', :to => 'users#new'
  
  match 'account', :to=>'users#edit'

  resources :posts
  resources :pages
  resource :user_session
  
  resources :password_resets
  
  resources :galleries 
  resources :photos 
  
  resources :sponsors
  
  resources :sponsors do
     resources :photos    
  end
  
  
  resources :galleries do
    resources :photos 
  end
  
  resources :presentations 
 
  
  get "home/index"

  match 'blog/:id', :to=> 'posts#show'
  match ':id', :to=> 'pages#show', :id=>nil
    
    
    
  resources :home
  root :to => "home#index"

end

app/views/shared/_nav.html.haml
%ul
  %li
    =link_to "Home", "/", :class=> @current_path=="/" ? "active" : "normal"
  %li
    =link_to "About", "/about", :class=> @current_path=="/about" ? "active" : "normal"
  %li 
    =link_to "Events", "/events", :class=> @current_path=="/events" ? "active" : "normal"
  %li 
    =link_to "Speakers", "/speakers", :class=> @current_path=="/speakers" ? "active" : "normal"
  %li 
    =link_to "Sponsors", "/sponsors" , :class=> @current_path=="/sponsors" ? "active" : "normal"
  %li 
    =link_to "Presentations", "/presentations" , :class=> @current_path=="/presentations" ? "active" : "normal"
    
  -if current_user and current_user.is_admin 
    %li
      =link_to "Pages", pages_url
    %li
      =link_to "Posts", posts_url
  -if current_user
    %li 
      = link_to "Account", account_url
    %li
      = link_to "Logout", logout_url
  -#%li 
    =#link_to "Register", "/"
  -#%li 
    =#link_to "Contact", "/"
    

app/views/shared/_sidebar.html.haml
#sidebar
  %h3.sponsors_text Sponsors
  %ul.sponsors
    -if @sidebar_sponsors and @sidebar_sponsors.size > 0 
      - @sidebar_sponsors.each do |s|
        -s_image = image_tag s.photos.first.image.url rescue nil 
        %li{:class=>s.name.downcase.gsub(" ", "")+"_image"}=link_to s_image, s.link, :target=>"_blank"   

  =link_to "Read About The Sponsors", "/sponsors", :class=>"about_sponsors_link"