config/routes.rb
Railsjam::Application.routes.draw do

  match 'logout', :to => 'user_sessions#destroy', :as => "logout"
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'not_found', :to=>"home#page_not_found", :as=>"not_found"

  


  resources :attachments 
  resources :events
  resources :events do
    resource :attendees
  end

  resources :users
  match '/signup', :to => 'users#new'
  
  match 'account', :to=>'users#edit'

  resources :posts
  resources :pages
  resource :user_session
  
  resources :password_resets
  
  resources :galleries 
  resources :photos 
  
  resources :sponsors
  
  resources :sponsors do
     resources :photos    
  end
  
  
  resources :galleries do
    resources :photos 
  end
  
  resources :presentations 
 
  
  get "home/index"

  match 'blog/:id', :to=> 'posts#show'
  match ':id', :to=> 'pages#show', :id=>nil
    
    
    
  resources :home
  root :to => "home#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  validates :name, :presence => true
  
  has_many :users, :through => :attendees
  has_many :attendees
  has_many :presentations 
  has_friendly_id :name, :use_slug => true

  has_many :photos, :as => 'photoable', :dependent => :destroy
  accepts_nested_attributes_for :photos

  belongs_to :user

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  filter_access_to :all
  
  def index
    @events = Event.order("created_at DESC")
  end
  
  def show
    @event = Event.find(params[:id])
    @title = @event.name
  end
  
  def new
    @event = Event.new
    @event.photos.build if @event.photos.blank?
  end
  
  
  def edit
    @event = Event.find(params[:id])
    @event.photos.build if @event.photos.blank?
  end
  
  def create
    @event = Event.new(params[:event])
    respond_to do |format|
      if @event.save
        format.html { redirect_to(@event, :notice => 'Event was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
    
  end
  
  def update
    @event = Event.find(params[:id])
    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to(@event, :notice => 'Event was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end    
    
  end
  
  
  
end

app/views/events/_form.html.haml
= form_for @event, :html=>{:multipart=>true} do |f|
  = render "shared/error_messages", :target => @event
  .field
    = f.label :name
    = f.text_field :name, :class=>"nice_field"
  .field
    = f.label :starts_at
    = f.datetime_select :starts_at
  .field
    = f.label :ends_at
    = f.datetime_select :ends_at
  .field
    = f.label :description
    = f.text_area :description, :class=>"textarea"
  .field
    = f.label :location
    = f.text_field :location, :class=>"nice_field"
  .field 
    %p Add an image of the location
    =render "photo_field", :p=>p
  .field
    = f.label :school
    = f.text_field :school, :class=>"nice_field"

  %input{:name => "event[user_id]", :type => "hidden", :value => current_user.id }
    
  = f.submit params[:id] ? "Update" : "Create", :class=>"button"

app/views/events/_photo_field.html.haml
%div{:id=>p ? "file_field#{p.id}" : "file_field", :class=>"attach_file"}
  %label{:for => "event_photo_attributes_0_file"} File
  %input{:name => "event[photos_attributes][0][image]", :type => "file", :class=>"file_field"}/

  -if p
    %input{:name => "event[photos_attributes][0][id]", :type => "hidden", :value => p.id }/

app/views/events/index.html.haml
-content_for :sidebar do
  =render :partial => "shared/sidebar"
  
.body
  %h2 Events
  - @events.each do |event|
    %h3
      = link_to event.name, event_path(event)
    %p
      = event.description
    -if current_user
      -unless Attendee.is_registered(current_user.id,event.id)
        = link_to 'Sign-Up', new_event_attendees_path(event), :class=>"button"
      -else
        %p.notice Hey thanks, you've already signed up for this event.
    -else
      = link_to 'Sign-Up', new_event_attendees_path(event), :class=>"button"
    =link_to "Show attendees", event_attendees_url(event), :class=>"button" if permitted_to? :index, :attendees

    %br
    %br

app/views/events/new.html.haml
%h1 
  New Event
=render :partial => "events/form"
%br/

app/views/events/show.html.haml
-content_for :sidebar do
  =render :partial => "shared/sidebar"
  
.body
  %h2= @event.name

  %p
    = @event.description
    = image_tag @event.photos.first.image.url rescue nil

  -if current_user
    -unless Attendee.is_registered(current_user.id,@event.id)
      = link_to 'Sign-Up', new_event_attendees_path(@event), :class=>"button"
    -else
      %p.notice Hey thanks, you've already signed up for this event.