config/routes.rb
Railsjam::Application.routes.draw do

  match 'logout', :to => 'user_sessions#destroy', :as => "logout"
  match 'login', :to => 'user_sessions#new', :as => "login"
  match 'not_found', :to=>"home#page_not_found", :as=>"not_found"

  


  resources :attachments 
  resources :events
  resources :events do
    resource :attendees
  end

  resources :users
  match '/signup', :to => 'users#new'
  
  match 'account', :to=>'users#edit'

  resources :posts
  resources :pages
  resource :user_session
  
  resources :password_resets
  
  resources :galleries 
  resources :photos 
  
  resources :sponsors
  
  resources :sponsors do
     resources :photos    
  end
  
  
  resources :galleries do
    resources :photos 
  end
  
  resources :presentations 
 
  
  get "home/index"

  match 'blog/:id', :to=> 'posts#show'
  match ':id', :to=> 'pages#show', :id=>nil
    
    
    
  resources :home
  root :to => "home#index"

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  
  validates :name , :presence=>true, :uniqueness=>true
  validates :description, :presence=>true
  validates :link, :presence=>true, :link=>true
  
  has_many :photos, :as => 'photoable', :dependent => :destroy
  accepts_nested_attributes_for :photos, :allow_destroy => true 
  
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  
  filter_access_to :all
    
  before_filter :find_sponsor, :only => [:show, :edit, :update, :destroy]


  def index
    
    
    @sponsors = Sponsor.all

    respond_to do |wants|
      wants.html 
    end
  end


  def show
    respond_to do |wants|
      wants.html 
    end
  end


  def new
    @sponsor = Sponsor.new
    1.times { @sponsor.photos.build }
    respond_to do |wants|
      wants.html 
    end
  end


  def edit
    
    if @sponsor.photos and @sponsor.photos.size == 0
      1.times { @sponsor.photos.build }      
    end
        
  end


  def create
    @sponsor = Sponsor.new(params[:sponsor])

    respond_to do |wants|
      if @sponsor.save
        flash[:notice] = 'Sponsor was successfully created.'
        wants.html { redirect_to sponsors_url }

      else
        wants.html { render :action => "new" }

      end
    end
  end


  def update
    respond_to do |wants|
      if @sponsor.update_attributes(params[:sponsor])
        flash[:notice] = 'Sponsor was successfully updated.'
        wants.html { redirect_to sponsors_url }

      else
        wants.html { render :action => "edit" }

      end
    end
  end


  def destroy
    @sponsor.destroy

    respond_to do |wants|
      wants.html { redirect_to(sponsors_url) }
      wants.xml  { head :ok }
    end
  end

  private
    def find_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

end

app/views/sponsors/_form.html.haml
= form_for @sponsor, :html=>{:multipart=>true} do |f|
  = render "shared/error_messages", :target => @sponsor 
  .field
    = f.label :name
    = f.text_field :name, :class=>"input"
  .field
    = f.label :link
    = f.text_field :link, :class=>"input"
  .field
    = f.label :description
    = f.text_area :description, :class=>"textarea"
  



  -if @sponsor.photos and @sponsor.photos.size > 0 and  @sponsor.photos[0].image and !@sponsor.photos[0].image.url.include?('missing')
    -@sponsor.photos.each do |p|
      %li{:id=>"file"+p.id.to_s}
        =image_tag p.image.url, :width=>100
        =link_to "Delete", photo_url(p.id), :method=>:delete, :confirm=>"Are you sure you want to delete this photo?", :remote=>:true, :class=>"alert"
      =render "photo_field", :p=>p
  
  .field 
    %p Add an image for the sponsor
    =render "photo_field", :p=>p
    
  .actions
    = f.submit 'Save', :class=>"button"

app/views/sponsors/_photo_field.html.haml
%div{:id=>p ? "file_field#{p.id}" : "file_field", :class=>"attach_file"}
  %label{:for => "sponsor_photo_attributes_0_file"} File
  %input{:name => "sponsor[photos_attributes][0][image]", :type => "file", :class=>"file_field"}/

  -if p
    %input{:name => "sponsor[photos_attributes][0][id]", :type => "hidden", :value => p.id }/

app/views/sponsors/edit.html.haml
%h1 Edit Sponsor

= render 'form'
.show-links
  =link_to 'Back', posts_path
  = link_to 'Help', "http://redcloth.org/textile/writing-paragraph-text/", :target=>"_blank"

app/views/sponsors/index.html.haml
-content_for :sidebar do
  =render :partial => "shared/sidebar"
  
.body
  %h2 About The Sponsors
  - @sponsors.each do |s|
    %h3
      = link_to s.name, s.link, :target=>"_blank"
    =raw RedCloth.new(s.description).to_html 
    - permitted_to? :edit, :sponsors do
      = link_to 'Edit', edit_sponsor_url(s)

app/views/sponsors/new.html.haml
%h1 New Sponsor

= render 'form'
.show-links
  =link_to 'Back', posts_path
  = link_to 'Help', "http://redcloth.org/textile/writing-paragraph-text/", :target=>"_blank"